GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"author": "Bruce Wayne",
	"url": "https://batman.fandom.com/wiki/Batman",
	"title": "Batman",
	"likes": 199
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"author": "Bruce Wayne",
	"url": "https://batman.fandom.com/wiki/The_Joker",
	"title": "The Joker",
	"likes": 203
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"author": "Test",
	"url": "https://test.com",
	"title": "Test"
}

###
DELETE http://localhost:3003/api/blogs/3

###
PUT http://localhost:3003/api/blogs/1
Content-Type: application/json

{
	"likes": "abcd"
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
	"author": "Test",
	"title": "Test"
}

###
# Tasks 13.8. - 13.12.
GET http://localhost:3003/api/users

###
# Creating username "batman"
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "batman@jl.com",
	"name": "Bruce Wayne"
}

###
# Creating username "superman"
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "superman@jl.com",
	"name": "Clark Kent"
}


###
PUT http://localhost:3003/api/users/kal-el
Content-Type: application/json

{
	"username": "superman"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "test@test.com",
	"name": "Test"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "test2@test",
	"name": "Test2"
}

###
POST http://localhost:3003/api/login
Content-Type: application/json

{
	"username": "batman@jl.com",
	"password": "batman"
}

###
# "batman" creating a new blog
POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdG1hbkBqbC5jb20iLCJpZCI6MSwiaWF0IjoxNjk4NTc0NzIzfQ.jCCaTVELt2El0FS2TTtV7zTglBNHt2-QGAedOiyt9IA
Content-Type: application/json

{
	"author": "Test",
	"url": "https://test.com",
	"title": "Test 5",
	"year": 1995
}

###
# Invalid deletion: "superman" tries to delete a blog created by "batman"
DELETE http://localhost:3003/api/blogs/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVybWFuIiwiaWQiOjIsImlhdCI6MTY5ODU1OTgzMX0.QdlHbCZEAJMn0mF7h7sXa365nkux2szx91GOgtG0xks

###
# Valid deletion: "batman" tries to delete a blog created by "batman"
DELETE http://localhost:3003/api/blogs/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJhdG1hbiIsImlkIjoxLCJpYXQiOjE2OTg1NjAwNzR9.jOGj8zKbKb67fc30kLqsXjOIhj_neSwyQ3BpRnBHHvc

###
# User "superman" adds new blogs
POST http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InN1cGVybWFuIiwiaWQiOjIsImlhdCI6MTY5ODU1OTgzMX0.QdlHbCZEAJMn0mF7h7sXa365nkux2szx91GOgtG0xks
Content-Type: application/json

{
	"author": "Test",
	"url": "https://test.com",
	"title": "测试 7",
	"likes": 5
}

###
GET http://localhost:3003/api/blogs?search=test

###
GET http://localhost:3003/api/blogs

###
GET http://localhost:3003/api/authors